#!/bin/sh
echo Killing appbin processes..
pkill appbin_daemon
pkill appbin_7z
pkill appbin_nw

echo Deleting shortcuts..

cat > ./appbin-sc.desktop << EOF
[Desktop Entry]
Name=Appbin
Icon=$HOME/.appbin/program_files/appbin.png
Exec=$HOME/.appbin/program_files/appbin
Path=$HOME/.appbin/program_files
GenericName=Appbin - Sync Applications Seamlessly
Type=Application
EOF

cat > ./appbin-dir.directory << EOF
[Desktop Entry]
Version=1.0
Name=Appbin
Icon=$HOME/.appbin/program_files/appbin.png
Type=Directory
EOF

xdg-desktop-menu uninstall appbin-dir.directory appbin-sc.desktop
xdg-desktop-icon uninstall appbin-sc.desktop
xdg-desktop-menu uninstall $HOME/.appbin/program_files/lin_sc/appbin-dir.directory $HOME/.appbin/program_files/lin_sc/*.desktop
xdg-desktop-icon uninstall $HOME/.appbin/program_files/lin_sc/*.desktop

echo Deleting files..

rm appbin-dir.directory appbin-sc.desktop
rm -rf $HOME/.appbin

echo Done.
read
